project:
  type: website

website:
  title: "Len MacGillivray Group Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: About Len
        href: about/about.qmd
      - text: Group Presentations
        href: presentations/blog.qmd
      - text: Papers
        href: papers/papers.qmd
      - text: Packages
        menu:
          - text: MacGillivray Group Packages
            href: packages/packages.qmd
          - text: Helpful packages for crystal engineering
            href: packages/others.qmd
      
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
